"""What actually happened at the edge.

Two tables, two jobs, and the split between them is the whole design:

* :class:`RequestLog` is one row per request, parsed from Caddy's JSON access
  log. It answers question-level queries — *which client got the 502s* — and it
  is expensive, so it is kept for hours, not months.
* :class:`RouteRollup` is one row per route per minute, folded up from those
  rows. It answers every chart and every time range, it is three orders of
  magnitude smaller, and it is what survives retention.

A dashboard reading `RequestLog` for a 30-day range would be scanning tens of
millions of rows to draw a line with 720 points on it. Reading rollups, it
scans 720 per route. That is why the collector writes both.

Percentiles are the reason the rollup carries latency *buckets* rather than an
average. An average of averages is not an average, and a P95 of P95s is not a
percentile at all — so the rollup stores a histogram, and
`app/services/analytics.py` interpolates across the summed buckets.
"""

from __future__ import annotations

from sillo.record import Model
from tortoise import fields

__all__ = [
    "LATENCY_BUCKETS_MS",
    "Alert",
    "Anomaly",
    "RequestLog",
    "RouteRollup",
    "bucket_for",
]


#: Upper bounds, in milliseconds, of the eleven latency buckets in a rollup.
#: Chosen so the interesting range for an API gateway — 5ms to 2s — gets nine
#: of them, and the two tails absorb everything else. Changing this list
#: invalidates existing rollups, so it is a constant rather than a setting.
LATENCY_BUCKETS_MS = (5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000)


def bucket_for(latency_ms: float) -> int:
    """Which bucket index a latency falls in. The last index is the overflow."""
    for index, bound in enumerate(LATENCY_BUCKETS_MS):
        if latency_ms <= bound:
            return index
    return len(LATENCY_BUCKETS_MS)


class RequestLog(Model):
    """One request, as Caddy logged it.

    Every column here comes from the access log. Nothing is inferred and
    nothing is fabricated: if Caddy did not log it, it is null. That matters
    because this table is the evidence behind the security screens, and a
    guessed field in an incident review is worse than a missing one.

    Deliberately absent: request and response *bodies*, cookies, and the
    `Authorization` header. The collector drops them before they reach here —
    see `app/collector/access_log.py`, which is the only writer.
    """

    id = fields.BigIntField(pk=True)
    gateway = fields.ForeignKeyField(
        "models.Gateway", related_name="requests", on_delete=fields.CASCADE
    )
    #: Nullable: a request that matched no Janus route still gets logged, and
    #: that is exactly the traffic a 404-scanning check looks for.
    route = fields.ForeignKeyField(
        "models.GatewayRoute", related_name="requests", null=True, on_delete=fields.SET_NULL
    )
    upstream = fields.ForeignKeyField(
        "models.Upstream", related_name="requests", null=True, on_delete=fields.SET_NULL
    )
    client = fields.ForeignKeyField(
        "models.Client", related_name="requests", null=True, on_delete=fields.SET_NULL
    )
    api_key = fields.ForeignKeyField(
        "models.ApiKey", related_name="requests", null=True, on_delete=fields.SET_NULL
    )

    occurred_at = fields.DatetimeField(index=True)
    method = fields.CharField(max_length=10, index=True)
    host = fields.CharField(max_length=255, index=True)
    path = fields.CharField(max_length=1000)
    status = fields.IntField(index=True)
    #: Round-trip duration in milliseconds, as Caddy measured it.
    latency_ms = fields.FloatField(default=0.0)
    bytes_in = fields.BigIntField(default=0)
    bytes_out = fields.BigIntField(default=0)

    client_ip = fields.CharField(max_length=64, index=True)
    user_agent = fields.CharField(max_length=400, null=True)
    referer = fields.CharField(max_length=500, null=True)
    protocol = fields.CharField(max_length=16, null=True)

    #: What the edge did beyond proxying: `blocked`, `rate_limited`,
    #: `unauthorized`, `maintenance`, or empty for a normal request. This is
    #: what separates "a 403 the upstream returned" from "a 403 Janus's policy
    #: produced", which are different incidents with the same status code.
    edge_action = fields.CharField(max_length=20, default="", index=True)
    #: Which rule produced that action, for the incident trail.
    matched_policy_id = fields.IntField(null=True)
    matched_rule_id = fields.IntField(null=True)

    #: True for rows generated by the demo data seeder rather than ingested
    #: from a real access log. Carried on the row, not inferred from the
    #: environment, so a database that has held both can still tell them apart
    #: — and so the UI can say so on the screen.
    simulated = fields.BooleanField(default=False, index=True)

    class Meta:
        table = "request_logs"
        indexes = (
            ("gateway_id", "occurred_at"),
            ("route_id", "occurred_at"),
            ("status", "occurred_at"),
            ("client_ip", "occurred_at"),
        )

    def __str__(self) -> str:
        return f"{self.method} {self.path} {self.status}"


class RouteRollup(Model):
    """One route's traffic in one minute.

    The grain is a minute because that is the finest resolution any Janus chart
    draws, and because a coarser grain cannot be re-cut: 15-minute buckets
    cannot answer a 15-minute window aligned to *now*. Longer ranges are
    aggregated up from these at query time.

    A row with a null route is traffic that matched no route — it still counts
    toward the gateway's totals, and it is where scanning shows up.
    """

    id = fields.BigIntField(pk=True)
    gateway = fields.ForeignKeyField(
        "models.Gateway", related_name="rollups", on_delete=fields.CASCADE
    )
    route = fields.ForeignKeyField(
        "models.GatewayRoute", related_name="rollups", null=True, on_delete=fields.CASCADE
    )
    #: Truncated to the minute, always UTC.
    minute = fields.DatetimeField(index=True)

    requests = fields.BigIntField(default=0)
    #: Status classes, counted separately so an error rate never needs the
    #: request table. `status_2xx + 3xx + 4xx + 5xx` equals `requests`.
    status_1xx = fields.BigIntField(default=0)
    status_2xx = fields.BigIntField(default=0)
    status_3xx = fields.BigIntField(default=0)
    status_4xx = fields.BigIntField(default=0)
    status_5xx = fields.BigIntField(default=0)

    #: Individually interesting statuses, kept as their own counters because
    #: the error screen breaks them out and deriving them from the request
    #: table would defeat the point of the rollup.
    status_401 = fields.BigIntField(default=0)
    status_403 = fields.BigIntField(default=0)
    status_404 = fields.BigIntField(default=0)
    status_429 = fields.BigIntField(default=0)
    status_502 = fields.BigIntField(default=0)
    status_503 = fields.BigIntField(default=0)
    status_504 = fields.BigIntField(default=0)

    blocked = fields.BigIntField(default=0)
    rate_limited = fields.BigIntField(default=0)
    timeouts = fields.BigIntField(default=0)

    bytes_in = fields.BigIntField(default=0)
    bytes_out = fields.BigIntField(default=0)

    #: Sum of latencies, for a weighted mean across any number of rows. Storing
    #: the sum rather than the mean is what makes rollups composable.
    latency_sum_ms = fields.FloatField(default=0.0)
    latency_max_ms = fields.FloatField(default=0.0)
    #: Eleven counters: the ten bounds in `LATENCY_BUCKETS_MS` plus overflow.
    #: A JSON list rather than eleven columns — it is read whole, written
    #: whole, and never filtered on.
    latency_buckets = fields.JSONField(default=list)

    #: How many distinct clients appeared in this minute. Approximate by
    #: nature: it is counted per minute and cannot be summed across minutes
    #: without double-counting, so the UI only ever shows it per-minute or
    #: recomputes uniques from the request table for short ranges.
    distinct_clients = fields.IntField(default=0)

    simulated = fields.BooleanField(default=False, index=True)

    class Meta:
        table = "route_rollups"
        unique_together = (("gateway_id", "route_id", "minute"),)
        indexes = (("gateway_id", "minute"),)

    def __str__(self) -> str:
        return f"route {self.route_id} @ {self.minute:%Y-%m-%d %H:%M} ({self.requests})"


class Alert(Model):
    """A threshold that has been crossed, and whether anyone dealt with it.

    Alerts are *stateful*: the evaluator opens one when a condition starts
    holding and resolves it when it stops, rather than emitting a row per
    evaluation. Without that, a five-minute outage at a one-minute evaluation
    interval is five alerts, and an operator learns to ignore the list.
    """

    id = fields.IntField(pk=True)
    gateway = fields.ForeignKeyField(
        "models.Gateway", related_name="alerts", null=True, on_delete=fields.CASCADE
    )
    route = fields.ForeignKeyField(
        "models.GatewayRoute", related_name="alerts", null=True, on_delete=fields.SET_NULL
    )
    upstream = fields.ForeignKeyField(
        "models.Upstream", related_name="alerts", null=True, on_delete=fields.SET_NULL
    )

    #: `error_rate_5xx`, `error_rate_4xx`, `latency_p95`, `upstream_unhealthy`,
    #: `traffic_spike`, `rate_limit_abuse`, `config_failed`, `sync_failed`.
    kind = fields.CharField(max_length=40, index=True)
    severity = fields.CharField(max_length=16, default="warning", index=True)
    title = fields.CharField(max_length=255)
    detail = fields.TextField(null=True)

    #: The number that tripped it, and the threshold it crossed. Both stored
    #: so a resolved alert still explains itself months later.
    observed = fields.FloatField(null=True)
    threshold = fields.FloatField(null=True)

    status = fields.CharField(max_length=16, default="open", index=True)
    opened_at = fields.DatetimeField(auto_now_add=True, index=True)
    resolved_at = fields.DatetimeField(null=True)
    acknowledged_at = fields.DatetimeField(null=True)
    acknowledged_by = fields.ForeignKeyField(
        "models.User", related_name="alerts", null=True, on_delete=fields.SET_NULL
    )

    class Meta:
        table = "alerts"
        indexes = (("status", "opened_at"),)

    def __str__(self) -> str:
        return self.title


class Anomaly(Model):
    """A statistical outlier — not, by itself, an incident.

    Kept apart from :class:`Alert` on purpose. An alert is a rule an operator
    wrote and a threshold they chose; an anomaly is Janus observing that
    something is unlike the recent past. Presenting the second as the first is
    how a dashboard teaches people to distrust it, so they are different
    tables, different screens and different words.
    """

    id = fields.IntField(pk=True)
    gateway = fields.ForeignKeyField(
        "models.Gateway", related_name="anomalies", on_delete=fields.CASCADE
    )
    route = fields.ForeignKeyField(
        "models.GatewayRoute", related_name="anomalies", null=True, on_delete=fields.SET_NULL
    )
    client = fields.ForeignKeyField(
        "models.Client", related_name="anomalies", null=True, on_delete=fields.SET_NULL
    )

    #: `traffic_spike`, `error_surge`, `latency_spike`, `new_client_volume`,
    #: `scanning`, `repeated_failures`.
    kind = fields.CharField(max_length=40, index=True)
    detail = fields.TextField(null=True)

    #: The observation, the recent baseline it is being compared against, and
    #: how many standard deviations separate them. Publishing all three is what
    #: makes the finding checkable rather than an assertion.
    observed = fields.FloatField(default=0.0)
    baseline = fields.FloatField(default=0.0)
    deviation = fields.FloatField(default=0.0)

    detected_at = fields.DatetimeField(auto_now_add=True, index=True)
    window_start = fields.DatetimeField(null=True)
    window_end = fields.DatetimeField(null=True)

    #: An operator's verdict: `unreviewed`, `benign`, `incident`. Promoting one
    #: to an incident is a human decision, which is why Janus never sets this.
    verdict = fields.CharField(max_length=16, default="unreviewed", index=True)

    class Meta:
        table = "anomalies"
        indexes = (("kind", "detected_at"),)

    def __str__(self) -> str:
        return f"{self.kind} ×{self.deviation:.1f}"
