"""Configuration versions, deployments and the audit trail.

Every change Janus makes to a gateway goes through a :class:`ConfigVersion`.
Nothing writes to Caddy without one, which is what makes `config history`,
`config diff` and `config rollback` possible: rolling back is not an undo
operation, it is deploying an earlier version that is still sitting in this
table with its full payload.
"""

from __future__ import annotations

import hashlib
import json as jsonlib
from typing import Any

from sillo.record import Model
from tortoise import fields

__all__ = ["AuditEvent", "ConfigVersion", "Deployment", "checksum_of"]


def checksum_of(payload: Any) -> str:
    """A stable digest of a configuration payload.

    `sort_keys` is what makes it stable: the same configuration built twice
    must produce the same checksum or drift detection reports a difference on
    every poll. `separators` removes the whitespace that would otherwise vary
    between producers.
    """
    encoded = jsonlib.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode()).hexdigest()


class ConfigVersion(Model):
    """A generated, validated Caddy configuration, and where it came from.

    The `payload` is the complete Janus-owned server object as it would be
    written to Caddy — not a diff, not a template. Storing it whole is what
    makes a rollback trustworthy: restoring version 14 means sending exactly
    the bytes version 14 sent, regardless of what the models say today.
    """

    id = fields.IntField(pk=True)
    gateway = fields.ForeignKeyField(
        "models.Gateway", related_name="versions", on_delete=fields.CASCADE
    )
    #: Monotonic per gateway, assigned by the configuration service inside a
    #: transaction. Not the primary key, because operators say "version 12 of
    #: the edge gateway" and mean the twelfth, not row 4,182.
    version = fields.IntField(index=True)

    payload = fields.JSONField()
    checksum = fields.CharField(max_length=64, index=True)

    #: `draft` → `validated` → `active` → `superseded`, or `rejected` when
    #: validation failed and `failed` when applying did. A version that never
    #: validated keeps its payload: reading why it was rejected is most of the
    #: value of recording it.
    status = fields.CharField(max_length=16, default="draft", index=True)

    #: What changed, in prose, for the history list. Generated by the diff in
    #: `app/services/configuration.py` rather than typed, so it cannot drift
    #: from the payload it describes.
    summary = fields.TextField(null=True)
    note = fields.TextField(null=True)

    #: Counts at generation time, so the history list can show the shape of a
    #: version without deserialising every payload.
    route_count = fields.IntField(default=0)
    upstream_count = fields.IntField(default=0)
    domain_count = fields.IntField(default=0)

    validation_error = fields.TextField(null=True)
    #: Set when this version was produced by rolling back to another.
    rolled_back_from_id = fields.IntField(null=True)

    author = fields.ForeignKeyField(
        "models.User", related_name="versions", null=True, on_delete=fields.SET_NULL
    )
    #: `web`, `cli`, or `system` for versions the drift reconciler generated.
    origin = fields.CharField(max_length=16, default="web")

    created_at = fields.DatetimeField(auto_now_add=True, index=True)
    activated_at = fields.DatetimeField(null=True)

    class Meta:
        table = "config_versions"
        unique_together = (("gateway_id", "version"),)
        ordering = ["-version"]

    def __str__(self) -> str:
        return f"v{self.version} ({self.status})"


class Deployment(Model):
    """One attempt to put a version onto a gateway.

    Separate from the version because the relationship is one-to-many: a
    version that failed to apply and was retried has two deployments, and the
    first one's error is the interesting record.
    """

    id = fields.IntField(pk=True)
    gateway = fields.ForeignKeyField(
        "models.Gateway", related_name="deployments", on_delete=fields.CASCADE
    )
    version = fields.ForeignKeyField(
        "models.ConfigVersion", related_name="deployments", on_delete=fields.CASCADE
    )

    #: `pending` → `validating` → `applying` → `verifying` → `succeeded`, or
    #: `failed` at whichever stage stopped. The stage names are the pipeline in
    #: `app/services/configuration.py`, so a stuck deployment says where.
    status = fields.CharField(max_length=16, default="pending", index=True)
    stage = fields.CharField(max_length=16, default="pending")
    error = fields.TextField(null=True)

    #: What was live before, so a failed apply can say what the gateway is
    #: still running rather than leaving an operator to guess.
    previous_version_id = fields.IntField(null=True)
    #: Whether Janus put the previous configuration back after a failure.
    rolled_back = fields.BooleanField(default=False)

    started_at = fields.DatetimeField(auto_now_add=True, index=True)
    finished_at = fields.DatetimeField(null=True)
    duration_ms = fields.IntField(null=True)

    actor = fields.ForeignKeyField(
        "models.User", related_name="deployments", null=True, on_delete=fields.SET_NULL
    )
    origin = fields.CharField(max_length=16, default="web")

    class Meta:
        table = "deployments"
        ordering = ["-started_at"]

    def __str__(self) -> str:
        return f"deploy v{self.version_id} — {self.status}"


class AuditEvent(Model):
    """Who did what, to which resource, and what it looked like before.

    `before` and `after` are the reason this table is worth having. An audit
    log that records "admin changed a rate limit" answers nothing during an
    incident; one that records the old and new values answers most of it.

    Written by `app/services/audit.py`, which is the only writer, and never
    updated or deleted by application code — an audit row that can be edited is
    not an audit row.
    """

    id = fields.BigIntField(pk=True)

    actor = fields.ForeignKeyField(
        "models.User", related_name="audit_events", null=True, on_delete=fields.SET_NULL
    )
    #: Kept as text alongside the foreign key so the trail survives the account
    #: being deleted. A null actor with `actor_label = "system"` is Janus
    #: itself — the scheduler reconciling drift, say.
    actor_label = fields.CharField(max_length=255, default="system")

    #: `route.created`, `ratelimit.updated`, `client.blocked`,
    #: `config.rolled_back`. Namespaced so the list can be filtered by
    #: resource without a second column to keep in step.
    action = fields.CharField(max_length=60, index=True)
    resource_type = fields.CharField(max_length=40, index=True)
    resource_id = fields.CharField(max_length=64, null=True)
    resource_label = fields.CharField(max_length=255, null=True)

    before = fields.JSONField(null=True)
    after = fields.JSONField(null=True)

    ip = fields.CharField(max_length=64, null=True)
    user_agent = fields.CharField(max_length=400, null=True)
    #: `web`, `cli`, `api`, `system`. Recorded because "who" is incomplete
    #: without "through what" — the same person acting through the CLI and the
    #: dashboard are different facts during a review.
    origin = fields.CharField(max_length=16, default="web", index=True)

    created_at = fields.DatetimeField(auto_now_add=True, index=True)

    class Meta:
        table = "audit_events"
        ordering = ["-created_at"]
        indexes = (("resource_type", "resource_id"), ("actor_id", "created_at"))

    def __str__(self) -> str:
        return f"{self.actor_label} {self.action} {self.resource_label or ''}".strip()
